# Generated by Django 5.1.5 on 2025-03-10 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория конкурса')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('age', models.PositiveBigIntegerField(verbose_name='Лет')),
                ('city', models.CharField(choices=[('tashkent', 'Ташкент'), ('qaraqalpakistan', 'Каракалпакистан'), ('andijan', 'Андижан'), ('buxara', 'Бухара'), ('djizakh', 'Жиззах'), ('fergana', 'Фергана'), ('qashqadaryo', 'Кашкадаря'), ('xorezm', 'Хорезм'), ('namangan', 'Наманган'), ('navoi', 'Навои'), ('samarkand', 'Самарканд'), ('surhandaryo', 'Сурхандаря'), ('sirdaryo', 'Сирдарья')], max_length=15, verbose_name='Город')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', ' Женский')], max_length=6, verbose_name='Пол')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коммент')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.contestcategory', verbose_name='Категория конкурса')),
            ],
        ),
    ]
